all : 
strlen_test : 
	gcc -Wall -Werror -Wextra -DPSTRLEN s21_string_test.c s21_string.c -o ../build/Quest_1 

strcmp_tests : 
	gcc -Wall -Werror -Wextra -DPCOMPARE s21_string_test.c s21_string.c -o ../build/Quest_2 

strcpy_tests : 
	gcc -Wall -Werror -Wextra -DPCOPY s21_string_test.c s21_string.c -o ../build/Quest_3 
clean : 
	rm -rf *o ../build/Quest_1 ../build/Quest_2 
rebuild : clean all